<?php
/**
 * @file
 * Provides Drupal coder integration.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implements hook_node_info().
 */
function drupal_scan_node_info() {
  return conduit_node_info_job('drupal_scan', t('Perform PHP syntax check and retrive list of tests.'));
}

/**
 * Implements hook_conduit_validate().
 */
function drupal_scan_conduit_validate(array $properties) {
  conduit_drupal_conduit_validate($properties);
}

/**
 * Implements hook_conduit_default_properties().
 */
function drupal_scan_conduit_default_properties() {
  return conduit_drupal_conduit_default_properties();
}

/**
 * Implements hook_conduit_queue_build().
 */
function drupal_scan_conduit_queue_build(array $properties) {
  return array(array());
}

/**
 * Implements hook_conduit_init().
 */
function drupal_scan_conduit_init($node, $chunk_count) {
  // Number of results cannot be predetermined.
}

/**
 * Implements hook_conduit_result().
 */
function drupal_scan_conduit_result($node, $delta, $result) {
  if (is_array($result) || $result == FALSE) {
    if ($node->conduit_status[LANGUAGE_NONE][0]['value'] == CONDUIT_STATUS_FAIL) {
      // @TODO Determine how we want to handle the context data.
      $node->conduit_summary[LANGUAGE_NONE][0]['value'] = t('Syntax errors found in the following file(s): @files',
        array('@files' => implode(', ', array_keys($result))));
    }
    else {
      // An empty array will not transfer properly so use FALSE.
      if ($result == FALSE) $result = array();
      $node->conduit_summary[LANGUAGE_NONE][0]['value'] = t('Found @count test cases', array('@count' => count($result)));
      foreach ($result as $class) {
        $node->conduit_result_drupal_scan_list[LANGUAGE_NONE][]['value'] = $class;
      }
    }
  }
  else {
    $node->conduit_summary[LANGUAGE_NONE][0]['value'] = $result;
  }
}

/**
 * Implements hook_views_api().
 */
function drupal_scan_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_pre_render().
 */
function drupal_scan_views_pre_render($view) {
  if (strpos($view->name, 'drupal_scan') === 0) {
    // Add conduit_drupal css to all drupal_scan views.
    drupal_add_css(drupal_get_path('module', 'conduit_drupal') . '/conduit_drupal.css');
  }
}
