<?php
/**
 * @file
 * Provides Drupal coder integration.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implements hook_node_info().
 */
function drupal_coder_node_info() {
  return conduit_node_info_job('drupal_coder', t('Perform a review of code.'));
}

/**
 * Implements hook_conduit_validate().
 */
function drupal_coder_conduit_validate(array $properties) {
  conduit_drupal_conduit_validate($properties);
}

/**
 * Implements hook_conduit_default_properties().
 */
function drupal_coder_conduit_default_properties() {
  return conduit_drupal_conduit_default_properties() + array(
    'reviews' => array('comment', 'sql', 'i18n', 'style', 'security'),
    'severity' => 'minor',
    'annotate' => FALSE,
  );
}

/**
 * Implements hook_conduit_queue_build().
 */
function drupal_coder_conduit_queue_build(array $properties) {
  return array(array());
}

/**
 * Implements hook_conduit_init().
 */
function drupal_coder_conduit_init($node, $chunk_count) {
  conduit_drupal_conduit_init($node, $chunk_count);
}

/**
 * Implements hook_conduit_result().
 */
function drupal_coder_conduit_result($node, $delta, $result) {
  conduit_drupal_conduit_result($node, $delta, $result);
}

/**
 * Implements hook_conduit_drupal_result_message().
 */
function drupal_coder_conduit_drupal_result_message($total) {
  return t('@critical critical, @normal normal, and @minor minor messages', array(
    '@critical' => $total[0],
    '@normal' => $total[1],
    '@minor' => $total[2],
  ));
}

/**
 * Implements hook_views_api().
 */
function drupal_coder_views_api() {
  return array(
    'api' => 3,
  );
}
