<?php
/**
 * @file
 * Provides Drupal coder integration.
 *
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implements hook_node_info().
 */
function drupal_coder_node_info() {
  return conduit_node_info_job('drupal_coder');
}

/**
 * Implements hook_conduit_validate().
 */
function drupal_coder_conduit_validate(array $properties) {
  conduit_drupal_conduit_validate($properties);
}

/**
 * Implements hook_conduit_default_properties().
 */
function drupal_coder_conduit_default_properties() {
  return conduit_drupal_conduit_default_properties() + array(
    'reviews' => array('comment', 'sql', 'i18n', 'style', 'security'),
    'severity' => 'minor',
    'annotate' => FALSE,
  );
}

/**
 * Implements hook_conduit_queue_build().
 */
function drupal_coder_conduit_queue_build(array $properties) {
  return array(array());
}

/**
 * Implements hook_conduit_init().
 */
function drupal_coder_conduit_init($node, $chunk_count) {
  // Number of results cannot be predetermined.
}

/**
 * Implements hook_conduit_result().
 */
function drupal_coder_conduit_result($node, $delta, $result) {
  if (is_array($result)) {
    foreach ($result as $file => $messages) {
      $node->conduit_result_drupal_summary[LANGUAGE_NONE][]['value'] = $file . ': @TODO';
      $delta = count($node->conduit_result_drupal_summary[LANGUAGE_NONE]) - 1;
      foreach ($messages as $message) {
        $node->conduit_result_drupal_delta[LANGUAGE_NONE][]['value'] = $delta;
        $node->conduit_result_drupal_line[LANGUAGE_NONE][]['value'] = $message['line'];
        $node->conduit_result_drupal_severity[LANGUAGE_NONE][]['value'] = $message['severity'];
        $node->conduit_result_drupal_message[LANGUAGE_NONE][]['value'] = $message['message'];
      }
    }
  }

  // Generate summary message.
  $node->conduit_summary[LANGUAGE_NONE][0]['value'] = '@TODO';
}
